apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-auth
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-auth
rules:
  - apiGroups:
    - certificates.k8s.io
    resources:
    - certificatesigningrequests
    - certificatesigningrequests/approval
    verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-auth
subjects:
  - kind: ServiceAccount
    name: cert-auth
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-auth
  labels:
    app: cert-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-auth
  template:
    metadata:
      labels:
        app: cert-auth
    spec:
      serviceAccountName: cert-auth
      containers:
      - image: justinbarrick/cert-auth:v0.1.0
        imagePullPolicy: IfNotPresent
        name: cert-auth
        env:
        - name: API_SERVER
          valueFrom:
            configMapKeyRef:
              name: cert-auth
              key: endpoint
---
apiVersion: v1
kind: Service
metadata:
  name: cert-auth
spec:
  ports:
  - name: cert-auth
    port: 8080
  selector:
    app: cert-auth
